name: agendamento
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  flutter_localizations: 
    sdk: flutter
  flutter_modular: ^5.0.3
  dart_date: ^1.2.2
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  rx_notifier: ^2.0.0+5
  brasil_fields: ^1.12.0
  firebase_auth: ^4.7.1
  intl: ^0.18.0
  time_span: ^2.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/img/

